execution:
    uuid: ccde1f41-4ddf-4968-8e68-36d2c5e9a8d8
    runtime:
        start: 2025-12-10T09:58:53.358122+01:00
        end: 2025-12-10T09:58:54.159667+01:00
        duration: 801545 microseconds
    execution_context:
        type: synchronous

action:
    type: visualizer
    plugin: !ref 'environment:plugins:rarefaction-depth'
    action: _beta_viz
    inputs: []
    parameters:
    -   max_range:
        - 1
        - 605
        - 1210
        - 1815
        - 2420
        - 3025
        - 3630
        - 4235
        - 4840
        - 5445
    -   kmer_run: false
    -   calc_array:
        - !!python/object/apply:numpy.core.multiarray.scalar
            - &id001 !!python/object/apply:numpy.dtype
                args:
                - f8
                - false
                - true
                state: !!python/tuple
                - 3
                - <
                - null
                - null
                - null
                - -1
                - -1
                - 0
            - !!binary |
                hGwFjVJixD8=
        - !!python/object/apply:numpy.core.multiarray.scalar
            - *id001
            - !!binary |
                x1gcYgjydT8=
        - !!python/object/apply:numpy.core.multiarray.scalar
            - *id001
            - !!binary |
                ErMju8scZT8=
        - !!python/object/apply:numpy.core.multiarray.scalar
            - *id001
            - !!binary |
                nQo95xPWXD8=
        - !!python/object/apply:numpy.core.multiarray.scalar
            - *id001
            - !!binary |
                OHk1huyDVz8=
        - !!python/object/apply:numpy.core.multiarray.scalar
            - *id001
            - !!binary |
                F3/NJUXqUT8=
        - !!python/object/apply:numpy.core.multiarray.scalar
            - *id001
            - !!binary |
                H6i0/2GOTD8=
        - !!python/object/apply:numpy.core.multiarray.scalar
            - *id001
            - !!binary |
                clEOZCWLQT8=
        - !!python/object/apply:numpy.core.multiarray.scalar
            - *id001
            - !!binary |
                AEF0GhiiVz8=
    -   metric: braycurtis
    -   algorithm: kneedle
    -   num_samples_left:
        - 34
        - 33
        - 27
        - 20
        - 18
        - 15
        - 14
        - 12
        - 9
        - 4
    output-name: visualization
    citations:
    - !cite 'action|rarefaction-depth:0+untagged.69.geaf0bae.dirty|visualizer:_beta_viz|0'

environment:
    platform: linux-x86_64
    python: |-
        3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21)
        [GCC 12.3.0]
    framework:
        version: 2024.5.1
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2024.5.1|0'
    plugins:
        rarefaction-depth:
            version: 0+untagged.69.geaf0bae.dirty
            website: https://github.com/andreahess99/automated-rarefaction-depth
            citations:
            - !cite 'plugin|rarefaction-depth:0+untagged.69.geaf0bae.dirty|0'
    python-packages:
        Brotli: 1.1.0
        Cython: 3.0.12
        DendroPy: 4.5.2
        MarkupSafe: 2.1.5
        PyJWT: 2.9.0
        PyNaCl: 1.5.0
        PyQt5: 5.15.9
        PyQt5-sip: 12.12.2
        PySocks: 1.7.1
        PyVCF3: 1.0.3
        PyYAML: 6.0.2
        Send2Trash: 1.8.3
        altair: 5.4.1
        anyio: 4.4.0
        appdirs: 1.4.4
        argcomplete: 3.5.0
        argh: 0.31.3
        argon2-cffi: 23.1.0
        argon2-cffi-bindings: 21.2.0
        arrow: 1.3.0
        astor: 0.8.1
        asttokens: 2.4.1
        atpublic: 3.1.2
        attrs: 24.2.0
        bcrypt: 4.2.0
        beautifulsoup4: 4.12.3
        bibtexparser: 1.4.1
        biom-format: 2.1.15
        biopython: '1.84'
        bleach: 6.1.0
        cachecontrol: 0.14.2
        cached-property: 1.5.2
        certifi: 2024.8.30
        cffi: 1.17.0
        charset-normalizer: 3.3.2
        click: 8.1.7
        colorama: 0.4.6
        comm: 0.2.2
        contourpy: 1.3.0
        cryptography: 43.0.1
        cutadapt: '4.9'
        cycler: 0.12.1
        deblur: 1.1.1
        debugpy: 1.8.5
        decorator: 4.4.2
        defusedxml: 0.7.1
        dill: 0.3.8
        dnaio: 1.2.1
        emperor: 1.0.4
        entrypoints: '0.4'
        exceptiongroup: 1.2.2
        executing: 2.1.0
        fastcluster: 1.2.6
        fastjsonschema: 2.20.0
        filelock: 3.15.4
        flufl-lock: 8.1.0
        fonttools: 4.53.1
        formulaic: 1.0.2
        fqdn: 1.5.1
        future: 1.0.0
        gffutils: 0.10.1
        globus-sdk: 3.44.0
        graphlib-backport: 1.0.3
        h2: 4.1.0
        h5py: 3.11.0
        hdmedians: 0.14.2
        hpack: 4.0.0
        hyperframe: 6.0.1
        idna: '3.8'
        ijson: 3.3.0
        importlib-metadata: 8.4.0
        importlib-resources: 6.4.4
        iniconfig: 2.0.0
        interface-meta: 1.3.0
        iow: 1.0.5
        ipykernel: 6.29.5
        ipython: 8.18.1
        ipython-genutils: 0.2.0
        ipywidgets: 8.1.5
        isal: 1.7.0
        isoduration: 20.11.0
        jedi: 0.19.1
        jinja2: 3.1.4
        joblib: 1.4.2
        jsonlines: 3.0.0
        jsonpointer: 3.0.0
        jsonschema: 4.23.0
        jsonschema-specifications: 2023.12.1
        jupyter-client: 7.4.9
        jupyter-core: 5.7.2
        jupyter-events: 0.10.0
        jupyter-server: 2.14.2
        jupyter-server-terminals: 0.5.3
        jupyterlab-pygments: 0.3.0
        jupyterlab-widgets: 3.0.13
        kiwisolver: 1.4.7
        kneed: 0.8.5
        llvmlite: 0.43.0
        lockfile: 0.12.2
        lxml: 5.2.2
        lz4: 4.3.3
        matplotlib: 3.8.4
        matplotlib-inline: 0.1.7
        mistune: 3.0.2
        msgpack: 1.1.0
        munkres: 1.1.4
        narwhals: 1.6.2
        natsort: 8.4.0
        nbclassic: 1.1.0
        nbclient: 0.10.0
        nbconvert: 7.16.4
        nbformat: 5.10.4
        ncbi-datasets-pylib: 14.25.1
        nest-asyncio: 1.6.0
        networkx: '3.1'
        nlopt: 2.8.0
        nose: 1.3.7
        notebook: 6.5.5
        notebook-shim: 0.2.4
        numba: 0.60.0
        numpy: 1.26.4
        overrides: 7.7.0
        packaging: '24.1'
        pandas: 2.2.2
        pandocfilters: 1.5.0
        paramiko: 3.4.1
        parsl: 2024.4.15
        parso: 0.8.4
        patsy: 0.5.6
        pexpect: 4.9.0
        pickleshare: 0.7.5
        pillow: 10.3.0
        pip: '24.2'
        pkgutil-resolve-name: 1.3.10
        platformdirs: 4.2.2
        pluggy: 1.5.0
        ply: '3.11'
        prometheus-client: 0.20.0
        prompt-toolkit: 3.0.47
        protobuf: 3.20.3
        psutil: 6.0.0
        ptyprocess: 0.7.0
        pure-eval: 0.2.3
        pycparser: '2.22'
        pyfaidx: 0.8.1.2
        pygments: 2.18.0
        pynndescent: 0.5.13
        pyparsing: 3.1.4
        pytest: 8.3.2
        python-dateutil: 2.8.2
        python-json-logger: 2.0.7
        pytz: '2024.1'
        pyzmq: 24.0.1
        q2-alignment: 2024.5.0
        q2-boots: 2024.10b0+4.g95b247b
        q2-composition: 2024.5.0
        q2-cutadapt: 2024.5.0
        q2-dada2: 2024.5.0
        q2-deblur: 2024.5.0
        q2-demux: 2024.5.0
        q2-diversity: 2024.5.1
        q2-diversity-lib: 2024.5.0
        q2-emperor: 2024.5.0
        q2-feature-classifier: 2024.5.0
        q2-feature-table: 2024.5.0
        q2-fragment-insertion: 2024.5.0
        q2-kmerizer: 0+untagged.29.gb64bddf
        q2-longitudinal: 2024.5.0
        q2-metadata: 2024.5.0
        q2-mystery-stew: 2024.5.0
        q2-phylogeny: 2024.5.0
        q2-quality-control: 2024.5.0
        q2-quality-filter: 2024.5.0
        q2-sample-classifier: 2024.5.0
        q2-taxa: 2024.5.0
        q2-types: 2024.5.0
        q2-vizard: 2025.4.0.dev0+90.ga641e5c
        q2-vsearch: 2024.5.0
        q2cli: 2024.5.0
        q2galaxy: 2024.5.0
        q2templates: 2024.5.0
        qiime2: 2024.5.1
        referencing: 0.35.1
        requests: 2.32.3
        rescript: 2024.5.1
        rfc3339-validator: 0.1.4
        rfc3986-validator: 0.1.1
        rpds-py: 0.20.0
        scikit-bio: 0.6.0
        scikit-learn: 1.4.2
        scipy: 1.10.1
        seaborn: 0.12.2
        sepp: 4.4.0
        setproctitle: 1.3.3
        setuptools: 73.0.1
        simplejson: 3.19.3
        sip: 6.7.12
        six: 1.16.0
        sniffio: 1.3.1
        soupsieve: '2.5'
        stack-data: 0.6.2
        statsmodels: 0.14.2
        tblib: 3.0.0
        terminado: 0.18.1
        threadpoolctl: 3.5.0
        tinycss2: 1.3.0
        toml: 0.10.2
        tomli: 2.0.1
        tomlkit: 0.13.2
        tornado: 6.4.1
        tqdm: 4.66.5
        traitlets: 5.9.0
        typeguard: 4.3.0
        types-python-dateutil: 2.9.0.20240821
        typing-extensions: 4.12.2
        typing-utils: 0.1.0
        tzdata: '2024.1'
        tzlocal: '2.1'
        umap-learn: 0.5.6
        unicodedata2: 15.1.0
        unifrac: 1.3.0
        uri-template: 1.3.0
        urllib3: 1.26.9
        vl-convert-python: 1.7.0
        wcwidth: 0.2.13
        webcolors: 24.8.0
        webencodings: 0.5.1
        websocket-client: 1.8.0
        wheel: 0.44.0
        widgetsnbextension: 4.0.13
        wrapt: 1.16.0
        xmltodict: 0.13.0
        xopen: 2.0.2
        yq: 3.4.3
        zipp: 3.20.1
        zlib-ng: 0.5.0
        zstandard: 0.23.0
        automated-rarefaction-depth: 0+untagged.69.geaf0bae.dirty
        autocommand: 2.2.2
        backports.tarfile: 1.2.0
        inflect: 7.3.1
        jaraco.context: 5.3.0
        jaraco.functools: 4.0.1
        jaraco.text: 3.12.1
        more-itertools: 10.3.0
